### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by jdlyw** [xmfbit/warpctc-caffe#10]
Makefile:587: recipe for target '.build_release/src/caffe/proto/caffe.pb.o' failed
make: *** [.build_release/src/caffe/proto/caffe.pb.o] Error 1

**Comment by xmfbit** [comment]
Could you provide more messages about the error? Information about your  building system / CUDA version / Makefile configuration are welcome.

**Comment by jdlyw** [comment]
the problem is sovled, but there is a new problem when make it 
src/caffe/3rdparty/reduce.cu(46): error: identifier "__shfl_down" is undefined

**Comment by xmfbit** [comment]
please refer to the issue #4 and #1

**Comment by jdlyw** [comment]
@xmfbit 能不能帮我联系一下 issue #4和 #1的提出者，我想问一下src/caffe/3rdparty/reduce.cu(46): error: identifier "__shfl_down" is undefined这个问题他是怎么解决的，我试了很多方法都不行，谢谢！

**Comment by shengyudingli** [comment]
@jdlyw  不好意思，时间过去的有点久了，都忘了当时怎么改的了……依稀记得是不同版本的toolkit的__shfl_down的实现不一样，你用的跟作者用的不一样，大概是这样的

**Comment by jdlyw** [comment]
谢谢大家，把安装CUDA9.0和cudnn7.1问题就解决了
