### ISSUE TITLE
build issue

### ISSUE THREAD

**Issue by yuechenfeng** [xmfbit/warpctc-caffe#11]
[  1%] Built target proto
[  1%] Building NVCC (Device) object src/caffe/CMakeFiles/cuda_compile.dir/layers/cuda_compile_generated_ctc_loss_layer.cu.o
/root/warpctc-caffe/src/caffe/layers/ctc_loss_layer.cu(14): error: explicit type is missing ("int" assumed)

/root/warpctc-caffe/src/caffe/layers/ctc_loss_layer.cu(14): error: type name is not allowed

/root/warpctc-caffe/src/caffe/layers/ctc_loss_layer.cu(14): error: expected a ";"

/root/warpctc-caffe/src/caffe/layers/ctc_loss_layer.cu(15): error: expression must have class type

/root/warpctc-caffe/src/caffe/layers/ctc_loss_layer.cu(16): error: expression must have class type

/root/warpctc-caffe/src/caffe/layers/ctc_loss_layer.cu(17): error: expression must have class type

/root/warpctc-caffe/src/caffe/layers/ctc_loss_layer.cu(26): error: no suitable constructor exists to convert from "int" to "ctcOptions"

/root/warpctc-caffe/src/caffe/layers/ctc_loss_layer.cu(37): error: namespace "std" has no member "accumulate"

/root/warpctc-caffe/src/caffe/layers/ctc_loss_layer.cu(41): error: expression must have class type

/root/warpctc-caffe/src/caffe/layers/ctc_loss_layer.cu(32): error: no suitable constructor exists to convert from "int" to "ctcOptions"
          detected during instantiation of "void caffe::CtcLossLayer<Dtype>::Forward_gpu(const std::vector<caffe::Blob<Dtype> *, std::allocator<caffe::Blob<Dtype> *>> &, const std::vector<caffe::Blob<Dtype> *, std::allocator<caffe::Blob<Dtype> *>> &) [with Dtype=float]"
(61): here

10 errors detected in the compilation of "/tmp/tmpxft_000058bc_00000000-6_ctc_loss_layer.cpp1.ii".
CMake Error at cuda_compile_generated_ctc_loss_layer.cu.o.cmake:266 (message):
  Error generating file
  /root/warpctc-caffe/Release/src/caffe/CMakeFiles/cuda_compile.dir/layers/./cuda_compile_generated_ctc_loss_layer.cu.o

src/caffe/CMakeFiles/caffe.dir/build.make:16157: recipe for target 'src/caffe/CMakeFiles/cuda_compile.dir/layers/cuda_compile_generated_ctc_loss_layer.cu.o' failed
make[2]: *** [src/caffe/CMakeFiles/cuda_compile.dir/layers/cuda_compile_generated_ctc_loss_layer.cu.o] Error 1
CMakeFiles/Makefile2:272: recipe for target 'src/caffe/CMakeFiles/caffe.dir/all' failed
make[1]: *** [src/caffe/CMakeFiles/caffe.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by yuechenfeng** [comment]
之后将auto 改为 ctcOptions之后依旧报错

/root/warpctc-caffe/src/caffe/layers/ctc_loss_layer.cu(14): error: type name is not allowed

/root/warpctc-caffe/src/caffe/layers/ctc_loss_layer.cu(14): error: expected a ";"

/root/warpctc-caffe/src/caffe/layers/ctc_loss_layer.cu(37): error: namespace "std" has no member "accumulate"

3 errors detected in the compilation of "/tmp/tmpxft_0000590c_00000000-6_ctc_loss_layer.cpp1.ii".
CMake Error at cuda_compile_generated_ctc_loss_layer.cu.o.cmake:266 (message):
  Error generating file
  /root/warpctc-caffe/Release/src/caffe/CMakeFiles/cuda_compile.dir/layers/./cuda_compile_generated_ctc_loss_layer.cu.o


src/caffe/CMakeFiles/caffe.dir/build.make:16157: recipe for target 'src/caffe/CMakeFiles/cuda_compile.dir/layers/cuda_compile_generated_ctc_loss_layer.cu.o' failed
make[2]: *** [src/caffe/CMakeFiles/cuda_compile.dir/layers/cuda_compile_generated_ctc_loss_layer.cu.o] Error 1
CMakeFiles/Makefile2:272: recipe for target 'src/caffe/CMakeFiles/caffe.dir/all' failed
make[1]: *** [src/caffe/CMakeFiles/caffe.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by xmfbit** [comment]
You could refer to #5 to fix it. Hope it works. If not, could you provide you building environment information? GCC / CUDA / OS will be welcome.

**Comment by yuechenfeng** [comment]
Done
