### ISSUE TITLE
some question about lstm 

### ISSUE THREAD

**Issue by zhou-zhiyuan** [xmfbit/warpctc-caffe#15]
你好，我有一个问题想问你，就是关于lstm层，我看了prototxt，lstm的输入是permute后的，形状是[80,1,3,30],然后训练出来这一层的h是400*90，c是400，权重是400*100，相当于100*100（因为有4组权重），那么输入的[80,1,3,30]如何和h400*90合并，然后合并之后又如何和100*100做卷积运算？

**Comment by zhou-zhiyuan** [comment]
这一层的h是400*90，c是400，权重400*100，相当于100*100（因为有4组权重），那么输入的[80,1,3,30]如何和400*90合并，然后合并之后又如何和100*100做卷积运算？

**Comment by zhou-zhiyuan** [comment]
这一层的h是[400,90]，c是400，权重[400,100]，相当于[100,100]（因为有4组权重），那么输入的[80,1,3,30]如何和[400,90]合并，然后合并之后又如何和[100,100]做卷积运算？

**Comment by xmfbit** [comment]
hi, zhiyuan, 感谢你对这个项目的关注。

1. 输入的shape的确是 `width x batch_size x channel x height`，这里将`width`作为sequence length。
2. 没太懂你所指“合并”是什么意思？这个sequence送到LSTM中后输出是`1 x batch_size x hidden_size`。
3. 然后其送到fc中，变成`1 x batch_size x C`，其中`C`是类别数 + 1 （因为有一个BLANK）

**Comment by zhou-zhiyuan** [comment]
对于2，我没表达清楚，我想说的是lstm内部的计算。http://colah.github.io/posts/2015-08-Understanding-LSTMs/  我在这个网页上看到lstm的计算过程，对于每扇门(gate)来说，输入其实是h[t-1]和x[t]的合并，按照项目的prototxt训练出来一个caffemodel，第一层lstm的h0是[400,90]，输入的x是[80,1,3,30]，那h0和x1如何拼接在一起输入lstm的各种门？

**Comment by xmfbit** [comment]
数学上，你可以参考：https://pytorch.org/docs/stable/generated/torch.nn.LSTM.html

具体实现上，每家框架可能都不太一样，你可以参考caffe的代码https://github.com/xmfbit/warpctc-caffe/blob/master/src/caffe/layers/lstm_layer.cpp

**Comment by zhou-zhiyuan** [comment]
多谢解答，我参照链接和源码看一下。
