### ISSUE TITLE
ERROR : src/caffe/3rdparty/reduce.cu(44): error: identifier "__shfl_down" is undefined

### ISSUE THREAD

**Issue by xiequnyi** [xmfbit/warpctc-caffe#4]
when i make the warpctc-caffe, there's a issue:
ERROR : src/caffe/3rdparty/reduce.cu(44): error: identifier "__shfl_down" is undefined

**Comment by xmfbit** [comment]
你试一下将Makefile.config里面的sm_20和sm_21相关的注释掉？貌似是旧的GPU架构不支持。 #1

**Comment by xt479910344** [comment]
你好，有没有该模型的测试文件

**Comment by xiequnyi** [comment]
不是很明白你的意思，本身有demo，可以跑一跑看看啊


发自网易邮箱大师
在2017年05月04日 17:44，xt479910344 写道:

你好，有没有该模型的测试文件

**Comment by xmfbit** [comment]
Hi， @xt479910344 你可以按照README中的方法测试一下关于不定长度验证码数字识别的Demo。这个repo目的是将百度美研提供的开源WarpCTC加入Caffe中，而这个Demo可以作为验证移植有效性的判断。具体内容请参考repo中的相应代码文件，谢谢。

**Comment by xmfbit** [comment]
@xiequnyi 谢谢你的支持。你的问题很可能是由于较旧的GPU架构不支持相应函数造成的。如果你按照我上面给出的建议还有问题的话，我可以提供我的Makefile作为参考。这个问题曾经在已关闭issue #1 中提到过。

**Comment by xiequnyi** [comment]
已经找到了关于缺失函数的声明和定义，已顺利编译通过，谢谢


发自网易邮箱大师
在2017年05月04日 18:08，Xiao Meifeng 写道:

@xiequnyi 谢谢你的支持。你的问题很可能是由于较旧的GPU架构不支持相应函数造成的。如果你按照我上面给出的建议还有问题的话，我可以提供我的Makefile作为参考。这个问题曾经在已关闭issue #1 中提到过。

**Comment by xiequnyi** [comment]
谢谢回复，我的问题已解决


发自网易邮箱大师
在2017年05月04日 18:06，Xiao Meifeng 写道:

Hi， @xt479910344 你可以按照README中的方法测试一下关于不定长度验证码数字识别的Demo。这个repo目的是将百度美研提供的开源WarpCTC加入Caffe中，而这个Demo可以作为验证移植有效性的判断。具体内容请参考repo中的相应代码文件，谢谢。

**Comment by af258963** [comment]
@xiequnyi 请问你的问题怎么解决的～，能否分享一下，谢谢

**Comment by jdlyw** [comment]
@xiequnyi 请问你在哪找到了关于缺失函数的声明和定义？急需你的帮助，谢谢

**Comment by xiequnyi** [comment]
你好，
    这个项目我做了蛮长时间了，细节的部分我不是很记得请了，不过您可以尝试些升级 cudnn 的版本至6，或许可以帮助您解决问题



qunyi_xie@163.com
 
From: 李云伟
Date: 2018-08-20 14:24
To: xmfbit/warpctc-caffe
CC: xiequnyi; Mention
Subject: Re: [xmfbit/warpctc-caffe] ERROR : src/caffe/3rdparty/reduce.cu(44): error: identifier "__shfl_down" is undefined (#4)
@xiequnyi 请问你在哪找到了关于缺失函数的声明和定义？急需你的帮助，谢谢

**Comment by jdlyw** [comment]
好的，我的cudnn的版本是7.1.4的，我再试试其他方法，谢谢
