### ISSUE TITLE
编译ctc_loss_layer.cu出错

### ISSUE THREAD

**Issue by wait1988** [xmfbit/warpctc-caffe#5]
出错信息如下：
NVCC src/caffe/3rdparty/reduce.cu
src/caffe/layers/ctc_loss_layer.cu: In instantiation of ‘void caffe::CtcLossLayer<Dtype>::Forward_gpu(const std::vector<caffe::Blob<Dtype>*>&, const std::vector<caffe::Blob<Dtype>*>&) [with Dtype = float]’:
src/caffe/layers/ctc_loss_layer.cu:61:135:   required from here
src/caffe/layers/ctc_loss_layer.cu:14:17: error: ‘std::initializer_list<_Tp> options’ has incomplete type
       auto options = ctcOptions{};
                 ^
make: *** [.build_release/cuda/src/caffe/layers/ctc_loss_layer.o] Error 1
make: *** Waiting for unfinished jobs....

**Comment by wait1988** [comment]
搞定，不用auto去推断

**Comment by ZizhenWang** [comment]
能不能说一下不用auto推断具体是怎么做的？我是新手不太懂这个，谢谢

**Comment by xmfbit** [comment]
@ZizhenWang 你的GCC版本号是？试着这样修改：
```
ctcOptions options{};
```
请参见：https://github.com/xmfbit/warpctc-caffe/blob/master/include/caffe/3rdparty/ctc.h#L38

**Comment by ZizhenWang** [comment]
@xmfbit 我的GCC版本是4.8.5，要在哪里修改呢？

**Comment by xmfbit** [comment]
编译报错的地方换掉。将`auto options = ctcOptions{};`换成上面的`ctcOptions options{};`。目前不清楚这个编译错误是否和具体编译器版本有关。

**Comment by ZizhenWang** [comment]
@xmfbit 我试一下，多谢大佬～
