### ISSUE TITLE
能否给一个测试的demo呢

### ISSUE THREAD

**Issue by wait1988** [xmfbit/warpctc-caffe#6]
训练过程没有问题，也生成了相应的model，但对这块儿东西不熟，能否提供一个测试的网络及程序呢

**Comment by xmfbit** [comment]
不好意思，暂时没有提供。因为我目前也没有做这方面的东西，所以时间上不是很抽得出来。您可以参考repo中`labelsquence_accuracy_layer`的相关实现，自己写一下。因为这个layer实际就是一个test model的过程。
