### ISSUE TITLE
CtcLoss的输入？

### ISSUE THREAD

**Issue by AllenDuane** [xmfbit/warpctc-caffe#9]
CtcLoss的两个输入中，fc1的输出是80×512×11的，那label的维度呢？
输入的时候我看到label是512×5的，没有看到经过哪一步骤改变啊。。。

**Comment by xmfbit** [comment]
你好。网络的原始输入label确实大小是batch_size x L。其中L取5，是因为最长的数字串长为5。对于长度小于5的，用BLANK补齐（这里我用的是10）。
在计算CTCLoss的时候，我们需要从原始label输入中获取到真正的label长度，这部分代码对应于`FlattenLabel()`函数，你可以参考[这里](https://github.com/xmfbit/warpctc-caffe/blob/master/src/caffe/layers/ctc_loss_layer.cpp#L38)。在这个函数中，我们会过滤掉末尾的BLANK，从而得到真正的label sequence。
这样做的原因是Caffe中的原生blob中每个batch的维度长度必须是一样的。

**Comment by AllenDuane** [comment]
@xmfbit  多谢啦~
